<?php echo $this->doctype();?>

<!DOCTYPE html>
<html>
<head>
	<?php $this->headTitle('XX管理中心')->setSeparator(' - ')->setAutoEscape(false); ?>
	<?php echo $this->headTitle(); ?>

	<?php $this->headMeta()->setCharset('UTF-8'); ?>
	<?php echo $this->headMeta(); ?>

	<?php $this->headLink()->appendStylesheet($this->basePath('element-ui/css/index.css')); ?>
	<?php $this->headLink()->appendStylesheet($this->basePath('iconfont/personalcenter/iconfont.css')); ?>
	<?php $this->headLink()->appendStylesheet($this->basePath('static/css/font_pcenter.css')); ?>
	<?php echo $this->headLink(); ?>
	
	<?php $this->inlineScript()->prependFile($this->basePath('static/js/personal-theme.js'));?>
	<?php $this->inlineScript()->prependFile($this->basePath('static/js/require.js'));?>
	<?php $this->inlineScript()->prependFile($this->basePath('static/js/jquery.js'));?>
	<?php $this->inlineScript()->prependFile($this->basePath('element-ui/js/index.js'));?>
	<?php $this->inlineScript()->prependFile($this->basePath('vue/vue.js'));?>
	
	<?php echo $this->inlineScript(); ?>
</head>
<body>
	<?php echo $this->content; ?>
</body>

</html>