<div style="width: 500px;margin:200px auto;"><h1>登录界面</h1>

<form action="/user/login" method="post">
<div>
	<label>用户名：</label><input name="user_name" type="text"></input>
</div>
<br/>
<div>
	<label>密&nbsp;&nbsp;&nbsp;&nbsp;码：</label><input name="user_pwd" type="password"></input>
</div>
<br/>
<div>
<input type="hidden" name="http_referer" value="1"></input>

<button type="submit">提交</button>
</div>
</form>
</div>