<?php echo $this->doctype();?>

<!DOCTYPE html>
<html>
<head>
	<?php $this->headTitle('XX管理中心')->setSeparator(' - ')->setAutoEscape(false); ?>
	<?php echo $this->headTitle(); ?>

	<?php $this->headMeta()->setCharset('UTF-8'); ?>
	<?php echo $this->headMeta(); ?>

	<?php $this->headLink()->appendStylesheet($this->basePath('element-ui/css/index.css')); ?>
	<?php $this->headLink()->appendStylesheet($this->basePath('iconfont/personalcenter/iconfont.css')); ?>
	<?php $this->headLink()->appendStylesheet($this->basePath('static/css/font_pcenter.css')); ?>
	<?php echo $this->headLink(); ?>
	
	<?php $this->inlineScript()->prependFile($this->basePath('static/js/personal-theme.js'));?>
	<?php $this->inlineScript()->prependFile($this->basePath('static/js/require.js'));?>
	<?php $this->inlineScript()->prependFile($this->basePath('static/js/jquery.js'));?>
	<?php $this->inlineScript()->prependFile($this->basePath('element-ui/js/index.js'));?>
	<?php $this->inlineScript()->prependFile($this->basePath('vue/vue.js'));?>
	
	<?php echo $this->inlineScript(); ?>
</head>
<body>

<div class="menu-wrapper">
<a href="#" class="logo">
	<img  class="logo-img" src="<?php echo $this->basePath('static/logo.png')?>">
</a>
<nav class="personal__menu">
<ul id="nav" role="menubar" class="menu">
	<li role="menu-item" class="item-PI level-0 _active" ys-haspopoup="false">
		<a href="#" onclick="return false;" class="icon-shezhi _active">
			<span>账户中心</span>
		</a>
		<div class="submenu">
			<strong class="submenu-title">账户中心</strong>
			<a href="#" class="action-close _close el-icon-close" data-role="close-submenu"></a>
			<ul role="menu">
				<li class="column">
					<ul role="menu">
						<li class="level-1 parent">
							<strong class="submenu-group-title">信息管理</strong>
							<div class="submenu">
								<ul role="menu">
									<li role="menu-item" class="level-2">
										<a href="#">个人信息</a>
									</li>
									<li role="menu-item" class="level-2">
										<a href="#">密码修改</a>
									</li>
									<li role="menu-item" class="level-2">
										<a href="#">实名认证</a>
									</li>
								</ul>
							</div>	
						</li><!--个人资料块-->
						<li class="level-1 parent">
							<strong class="submenu-group-title">子账户管理</strong>
							<div class="submenu">
								<ul role="menu">
									<li role="menu-item" class="level-2">
										<a href="#">子账户列表</a>
									</li>
									<li role="menu-item" class="level-2">
										<a href="#">创建子账户</a>
									</li>
									<li role="menu-item" class="level-2">
										<a href="#">子账户角色</a>
									</li>
								</ul>
							</div>	
						</li><!--子账户管理块-->
					</ul>	
				</li>
				<li class="column">
					<ul role="menu">
						<li class="level-1 parent">
							<div class="submenu">
								<strong class="submenu-group-title">系统中心</strong>
								<ul role="menu">
									<li role="menu-item" class="level-2">
										<a href="#">系统设置</a>
									</li>
								</ul>
							</div>	
						</li><!--系统设置块-->
					</ul>
				</li>
			</ul>
		</div>
	</li>
	<li role="menu-item" class="item-DM level-0" ys-haspopoup="true">
		<a href="#" onclick="return false;" class="icon-jijianfasong ">
			<span>直邮中心</span>
		</a>
		<div class="submenu">
			<strong class="submenu-title">直邮中心</strong>
			<a href="#" class="action-close _close el-icon-close" data-role="close-submenu"></a>
			<ul role="menu">
				<li class="level-1 parent">
					<ul role="menu">
						<li role="menu-item" class="level-2">
							<a href="#">订单列表</a>
						</li>
						<li role="menu-item" class="level-2">
							<a href="#" >物流查询</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</li>
	<li role="menu-item" class="item-PI level-0" ys-haspopoup="true">
		<a href="#" onclick="return false;" class="icon-zhongzhuanzhan ">
			<span>保税中心</span>
		</a>
		<div class="submenu">
			<strong class="submenu-title">保税中心</strong>
			<a href="#" class="action-close _close el-icon-close" data-role="close-submenu"></a>
			<ul role="menu">
				<li class="level-1 parent">
					<ul role="menu">
						<li role="menu-item" class="level-2">
							<a href="#">订单物流查询</a>
						</li>
						<li role="menu-item" class="level-2">
							<a href="#" >商品库存查询</a>
						</li>
						<li role="menu-item" class="level-2">
							<a href="#">出库信息</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</li>
</ul>
</nav>
</div>
	<?php echo $this->content; ?>
</body>

</html>